export const FETCH_PATIENTS_DATA_REQUEST = "FETCH_PATIENTS_DATA_REQUEST";
export const FETCH_PATIENTS_DATA_SUCCESS = "FETCH_PATIENTS_DATA_SUCCESS";
export const FETCH_PATIENTS_DATA_ERROR = "FETCH_PATIENTS_DATA_ERROR";
